### ISSUE TITLE
serviceworkerware missing traces

### ISSUE THREAD

**Issue by tukylarana** [arcturus/serviceworkerware#5]
Hi,

Not sure if there is an issue behind the behavior i'm seeing or not but just to double check, when i run http://localhost:8000/demo/index.html (with javascript console enabled) on Chrome Canary, i'm not able to see installation/activation traces, i'm only able to see sw traces if i inspect the specific sw process (and pid is only available once the sw is installed and activated :-)). Traces such as:
[ServiceWorkerWare] Event received: %s fetch
[ServiceWorkerWare] Applying middleware %s

However, when running NightlyDebug browser i see the following traces in the browser console:
"[ServiceWorkerWare]" "Event received: %s" "install"
"On install"
ReferenceError: caches is not defined
i'm not able to see i.e, OnActivate or OnMessage traces
Please feel free to contact me if further details are needed. Awesome work!. Thanks!

**Comment by arcturus** [comment]
Hi,

thanks for reporting, I'll need to investigate when the 'onInstall' event is fired in Chrome Canary.

**Comment by ferjm** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1155613
